config/routes.rb
Rails.application.routes.draw do
  resources :blends
  resources :strains
  resources :wines
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  'wines#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blend.rb
class Blend < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
end

app/models/strain.rb
class Strain < ApplicationRecord
    has_many :blends
    has_many :wines, through: :blends
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :blends
    has_many :strains, through: :blends  

    validate :check_percentage

    after_save :delete_blends_without_percentage

    accepts_nested_attributes_for :blends,
                                  allow_destroy: true,
                                  reject_if: proc { |attributes| attributes[:percentage].blank? }

    def check_percentage
        percentages = self.blends.map { |blend| blend.percentage }
        total_percentage = percentages.sum

        unless total_percentage == 100
            errors.add(:blends, "Los ensablajes deben sumar 100%")
        end
    end

    def delete_blends_without_percentage
        blends_without_percentage = self.blends.where(percentage: 0)
        unless blends_without_percentage.size < 1
            blends_without_percentage.destroy_all
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blends_controller.rb
class BlendsController < ApplicationController
  before_action :set_blend, only: %i[ show edit update destroy ]

  # GET /blends or /blends.json
  def index
    @blends = Blend.all
  end

  # GET /blends/1 or /blends/1.json
  def show
  end

  # GET /blends/new
  def new
    @blend = Blend.new
  end

  # GET /blends/1/edit
  def edit
  end

  # POST /blends or /blends.json
  def create
    @blend = Blend.new(blend_params)

    respond_to do |format|
      if @blend.save
        format.html { redirect_to blend_url(@blend), notice: "Blend was successfully created." }
        format.json { render :show, status: :created, location: @blend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blends/1 or /blends/1.json
  def update
    respond_to do |format|
      if @blend.update(blend_params)
        format.html { redirect_to blend_url(@blend), notice: "Blend was successfully updated." }
        format.json { render :show, status: :ok, location: @blend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blends/1 or /blends/1.json
  def destroy
    @blend.destroy

    respond_to do |format|
      format.html { redirect_to blends_url, notice: "Blend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blend
      @blend = Blend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blend_params
      params.require(:blend).permit(:percentage, :wine_id, :strain_id)
    end
end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
  before_action :set_strain, only: %i[ show edit update destroy ]

  # GET /strains or /strains.json
  def index
    @strains = Strain.all
  end

  # GET /strains/1 or /strains/1.json
  def show
  end

  # GET /strains/new
  def new
    @strain = Strain.new
  end

  # GET /strains/1/edit
  def edit
  end

  # POST /strains or /strains.json
  def create
    @strain = Strain.new(strain_params)

    respond_to do |format|
      if @strain.save
        format.html { redirect_to strain_url(@strain), notice: "Strain was successfully created." }
        format.json { render :show, status: :created, location: @strain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strains/1 or /strains/1.json
  def update
    respond_to do |format|
      if @strain.update(strain_params)
        format.html { redirect_to strain_url(@strain), notice: "Strain was successfully updated." }
        format.json { render :show, status: :ok, location: @strain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strains/1 or /strains/1.json
  def destroy
    @strain.destroy

    respond_to do |format|
      format.html { redirect_to strains_url, notice: "Strain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strain
      @strain = Strain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def strain_params
      params.require(:strain).permit(:name, :origin)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]
  before_action :set_strains, only: %i[new edit create update]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    @strains.size.times do
      @wine.blends.build
    end
  end

  # GET /wines/1/edit
  def edit
    strains_quantity = @wine.strains.size
    strains_iterations = @strains.size - strains_quantity
    strains_iterations.times do
      @wine.blends.build
    end 
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy

    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    def set_strains
      @strains = Strain.pluck(:name, :id)
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, :wineyard, :year, blends_attributes: [:id, :percentage, :strain_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blends_helper.rb
module BlendsHelper
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/blends/_form.html.erb
<%= form_with(model: blend) do |form| %>
  <% if blend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blend.errors.count, "error") %> prohibited this blend from being saved:</h2>

      <ul>
        <% blend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :percentage %>
    <%= form.number_field :percentage %>
  </div>

  <div class="field">
    <%= form.label :wine_id %>
    <%= form.text_field :wine_id %>
  </div>

  <div class="field">
    <%= form.label :strain_id %>
    <%= form.text_field :strain_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blends/edit.html.erb
<h1>Editing Blend</h1>

<%= render 'form', blend: @blend %>

<%= link_to 'Show', @blend %> |
<%= link_to 'Back', blends_path %>

app/views/blends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blends</h1>

<table>
  <thead>
    <tr>
      <th>Percentage</th>
      <th>Wine</th>
      <th>Strain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blends.each do |blend| %>
      <tr>
        <td><%= blend.percentage %></td>
        <td><%= blend.wine_id %></td>
        <td><%= blend.strain_id %></td>
        <td><%= link_to 'Show', blend %></td>
        <td><%= link_to 'Edit', edit_blend_path(blend) %></td>
        <td><%= link_to 'Destroy', blend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blend', new_blend_path %>

app/views/blends/new.html.erb
<h1>New Blend</h1>

<%= render 'form', blend: @blend %>

<%= link_to 'Back', blends_path %>

app/views/blends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Percentage:</strong>
  <%= @blend.percentage %>
</p>

<p>
  <strong>Wine:</strong>
  <%= @blend.wine_id %>
</p>

<p>
  <strong>Strain:</strong>
  <%= @blend.strain_id %>
</p>

<%= link_to 'Edit', edit_blend_path(@blend) %> |
<%= link_to 'Back', blends_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CepasGuiado</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/strains/_form.html.erb
<%= form_with(model: strain) do |form| %>
  <% if strain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(strain.errors.count, "error") %> prohibited this strain from being saved:</h2>

      <ul>
        <% strain.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/strains/edit.html.erb
<h1>Editing Strain</h1>

<%= render 'form', strain: @strain %>

<%= link_to 'Show', @strain %> |
<%= link_to 'Back', strains_path %>

app/views/strains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Strains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Origin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @strains.each do |strain| %>
      <tr>
        <td><%= strain.name %></td>
        <td><%= strain.origin %></td>
        <td><%= link_to 'Show', strain %></td>
        <td><%= link_to 'Edit', edit_strain_path(strain) %></td>
        <td><%= link_to 'Destroy', strain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Strain', new_strain_path %>

app/views/strains/new.html.erb
<h1>New Strain</h1>

<%= render 'form', strain: @strain %>

<%= link_to 'Back', strains_path %>

app/views/strains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @strain.name %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @strain.origin %>
</p>

<%= link_to 'Edit', edit_strain_path(@strain) %> |
<%= link_to 'Back', strains_path %>

app/views/wines/_form.html.erb
<%= form_with(model: wine) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
        <% wine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :wineyard %>
    <%= form.text_field :wineyard %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>
  
  <%= form.fields_for :blends do |blend| %>
    <div class="field">
      <%= blend.select :strain_id, @strains %>
      <%= blend.number_field :percentage %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Wineyard</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.wineyard %></td>
        <td><%= wine.year %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<p>
  <strong>Wineyard:</strong>
  <%= @wine.wineyard %>
</p>

<p>
  <strong>Year:</strong>
  <%= @wine.year %>
</p>

<% if @wine.strains.present? %>
<h3>Cepas:</h3>
<ul>
  <% @wine.blends.each do |blend| %>
  <li><strong><%= blend.strain.name %>:</strong> <%= blend.percentage %>%</li>
  <% end %>
</ul>
<% end %>


<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>